import { ipcRenderer } from 'electron'
import type { ApiAiQuickEvent, ApiAiTerminalEvent, ApiTestingBridge } from './shared/workspace'

export const apiTestingBridge: ApiTestingBridge = {
  getSpecSync: (scope) => ipcRenderer.invoke('api-testing:spec-sync', scope),
  deleteSpecAccount: (scope) => ipcRenderer.invoke('api-testing:delete-spec-account', scope),
  getRequestAuth: (scope) => ipcRenderer.invoke('api-testing:get-request-auth', scope),
  setRequestAuth: (scope, variable) => ipcRenderer.invoke('api-testing:set-request-auth', scope, variable),
  getAiChatStatus: (refresh) => ipcRenderer.invoke('api-testing:ai-chat-status', refresh),
  getAiChatSettings: (projectId) => ipcRenderer.invoke('api-testing:get-ai-chat-settings', projectId),
  saveAiChatSettings: (projectId, settings) => ipcRenderer.invoke('api-testing:save-ai-chat-settings', projectId, settings),
  chooseDirectories: () => ipcRenderer.invoke('api-testing:choose-directories'),
  getAiTerminal: (projectId) => ipcRenderer.invoke('api-testing:get-ai-terminal', projectId),
  startAiTerminal: (request) => ipcRenderer.invoke('api-testing:start-ai-terminal', request),
  resumeAiTerminal: (request) => ipcRenderer.invoke('api-testing:resume-ai-terminal', request),
  // Keystrokes and resizes are frequent and need no answer.
  writeAiTerminal: (projectId, data) => ipcRenderer.send('api-testing:write-ai-terminal', projectId, data),
  resizeAiTerminal: (projectId, size) => ipcRenderer.send('api-testing:resize-ai-terminal', projectId, size),
  clearAiTerminal: (projectId) => ipcRenderer.invoke('api-testing:clear-ai-terminal', projectId),
  checkAiTerminalResult: (scope) => ipcRenderer.invoke('api-testing:check-ai-terminal-result', scope),
  markAiTerminalResultSaved: (projectId, saved) => ipcRenderer.invoke('api-testing:mark-ai-terminal-result-saved', projectId, saved),
  refreshAiTerminalFiles: (scope) => ipcRenderer.invoke('api-testing:refresh-ai-terminal-files', scope),
  onAiTerminalEvent: (listener) => {
    const handler = (_event: Electron.IpcRendererEvent, value: ApiAiTerminalEvent) => listener(value)
    ipcRenderer.on('api-testing:ai-terminal-event', handler)
    return () => { ipcRenderer.removeListener('api-testing:ai-terminal-event', handler) }
  },
  askAiTerminal: (request) => ipcRenderer.invoke('api-testing:ask-ai-terminal', request),
  getAiQuick: (projectId) => ipcRenderer.invoke('api-testing:get-ai-quick', projectId),
  startAiQuick: (request) => ipcRenderer.invoke('api-testing:start-ai-quick', request),
  reviseAiQuick: (projectId, request) => ipcRenderer.invoke('api-testing:revise-ai-quick', projectId, request),
  stopAiQuick: (projectId) => ipcRenderer.invoke('api-testing:stop-ai-quick', projectId),
  clearAiQuick: (projectId) => ipcRenderer.invoke('api-testing:clear-ai-quick', projectId),
  markAiQuickResultSaved: (projectId, saved) => ipcRenderer.invoke('api-testing:mark-ai-quick-result-saved', projectId, saved),
  onAiQuickEvent: (listener) => {
    const handler = (_event: Electron.IpcRendererEvent, value: ApiAiQuickEvent) => listener(value)
    ipcRenderer.on('api-testing:ai-quick-event', handler)
    return () => { ipcRenderer.removeListener('api-testing:ai-quick-event', handler) }
  },
  copyAiPrompt: (request) => ipcRenderer.invoke('api-testing:copy-ai-prompt', request),
  getAiPrompt: (request) => ipcRenderer.invoke('api-testing:get-ai-prompt', request),
  readAiResult: (scope) => ipcRenderer.invoke('api-testing:read-ai-result', scope),
  checkAiScenarios: (scope, text) => ipcRenderer.invoke('api-testing:check-ai-scenarios', scope, text),
  getStorage: () => ipcRenderer.invoke('api-testing:get-storage'),
  getTeamSettings: () => ipcRenderer.invoke('api-testing:get-team-settings'),
  setShareSecrets: (on) => ipcRenderer.invoke('api-testing:set-share-secrets', on),
  importLocalProject: (projectId) => ipcRenderer.invoke('api-testing:import-local-project', projectId),
  listProjects: () => ipcRenderer.invoke('api-testing:list-projects'),
  saveProject: (project) => ipcRenderer.invoke('api-testing:save-project', project),
  deleteProject: (id) => ipcRenderer.invoke('api-testing:delete-project', id),
  deleteCatalog: (scope) => ipcRenderer.invoke('api-testing:delete-catalog', scope),
  deleteScenario: (projectId, id, revision) => ipcRenderer.invoke('api-testing:delete-scenario', projectId, id, revision),
  getCatalog: (scope) => ipcRenderer.invoke('api-testing:catalog', scope),
  importSpec: (scope, source) => ipcRenderer.invoke('api-testing:import', scope, source),
  execute: (scope, key, request) => ipcRenderer.invoke('api-testing:execute', scope, key, request),
  cancel: (scope) => ipcRenderer.invoke('api-testing:cancel', scope),
  listGlobals: (scope) => ipcRenderer.invoke('api-testing:list-globals', scope),
  setGlobal: (scope, name, value) => ipcRenderer.invoke('api-testing:set-global', scope, name, value),
  deleteGlobal: (scope, name) => ipcRenderer.invoke('api-testing:delete-global', scope, name),
  listCookies: (scope) => ipcRenderer.invoke('api-testing:list-cookies', scope),
  clearCookies: (scope) => ipcRenderer.invoke('api-testing:clear-cookies', scope),
  listScenarios: (projectId) => ipcRenderer.invoke('api-testing:list-scenarios', projectId),
  checkScenarioSpecs: (scope) => ipcRenderer.invoke('api-testing:check-scenario-specs', scope),
  applyTitleRenames: (scope) => ipcRenderer.invoke('api-testing:apply-title-renames', scope),
  keepTitles: (scope, scenarioId) => ipcRenderer.invoke('api-testing:keep-titles', scope, scenarioId),
  getDocInputs: (scope) => ipcRenderer.invoke('api-testing:get-doc-inputs', scope),
  forgetDocInput: (scope, key) => ipcRenderer.invoke('api-testing:forget-doc-input', scope, key),
  exportProject: (projectId) => ipcRenderer.invoke('api-testing:export-project', projectId),
  readProjectFile: () => ipcRenderer.invoke('api-testing:read-project-file'),
  planProjectImport: (text) => ipcRenderer.invoke('api-testing:plan-project-import', text),
  importProject: (text, update) => ipcRenderer.invoke('api-testing:import-project', text, update),
  listSuites: (projectId) => ipcRenderer.invoke('api-testing:list-suites', projectId),
  saveSuite: (projectId, suite, revision) => ipcRenderer.invoke('api-testing:save-suite', projectId, suite, revision),
  deleteSuite: (projectId, id, revision) => ipcRenderer.invoke('api-testing:delete-suite', projectId, id, revision),
  saveSuiteReport: (filename, html) => ipcRenderer.invoke('api-testing:save-suite-report', filename, html),
  readScenarioFile: () => ipcRenderer.invoke('api-testing:read-scenario-file'),
  previewScenario: (scope, source, bindings) => ipcRenderer.invoke('api-testing:preview-scenario', scope, source, bindings),
  saveScenario: (scope, source, bindings, revision, metadata) => ipcRenderer.invoke('api-testing:save-scenario', scope, source, bindings, revision, metadata),
  saveScenarioDraft: (scope, source, bindings, revision, metadata) => ipcRenderer.invoke('api-testing:save-scenario-draft', scope, source, bindings, revision, metadata),
  runScenario: (scope, source, bindings, inputs) => ipcRenderer.invoke('api-testing:run-scenario', scope, source, bindings, inputs),
  getPendingScenarioInput: (scope) => ipcRenderer.invoke('api-testing:get-pending-input', scope),
  submitScenarioInput: (scope, submission) => ipcRenderer.invoke('api-testing:submit-input', scope, submission),
}
